sajidkhurshidm-payroll-a42b661a948c/payrollado/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using payrollado.Models;

namespace payrollado.Controllers
{
    public class LoginController : Controller
    {
        payrollEntities4 db = new payrollEntities4();
        // GET: Login
        public ActionResult Index()
        {
            if (Session["EmployeeId"] == null)
            {

                var res = db.UserTypes.ToList();
                ViewBag.UserTypeId = new SelectList(res, "UserTypeId", "UserTypeName");
                return View();
            }
            return RedirectToAction("Index", "Employee");
        }
        [HttpPost]
        public ActionResult Index(LoginSinup model)
        {
          
            using (var db = new payrollEntities4())
            {
                var res = db.UserTypes.ToList();
                ViewBag.UserTypeId = new SelectList(res, "UserTypeId", "UserTypeName");
                if (ModelState.IsValid)
                {
                    var pas = Cryptography.Encrypt(model.Password);  
                    var q = db.Users.Where(x => x.UserName == model.UserName && x.Password == pas).FirstOrDefault();
                    if (q != null)
                    {
                        //var password = q.Password;
                        //var apppas = Cryptography.Decrypt(password);
                        //if(pas == apppas)
                        //{
                            Session["UserTypeId"] = q.UserTypeId;
                            Session["EmployeeId"] = q.EmployeeId;
                            Session["Username"] = q.UserName;
                            return RedirectToAction("Index", "Employee", new { Empid = Session["EmployeeId"] });
                        }
                        else
                        {
                            ViewBag.Msg = "User Name or Password is in not valid";
                            return View("Index");
                        }
                }
                else
                {
                    return View();
                }
            }
        }
        public ActionResult Sinup()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Sinup(LoginSinup model)
        {
            using (var db = new payrollEntities4())
            {
                User obj = new User()
                {
                    UserName = model.UserName,
                    Password = Cryptography.Encrypt(model.Password)
                };
                db.Users.Add(obj);
                db.SaveChanges();
                return View();
            }
        }
    }
}

sajidkhurshidm-payroll-a42b661a948c/payrollado/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using payrollado.Models;
namespace payrollado.Controllers
{
    public class MasterController : Controller
    {
        payrollEntities4 db = new payrollEntities4();
        // GET: Master  
        public ActionResult AddDepartment()
        {
            var query = db.Departments.ToList();
            List<SetupModel> list = new List<SetupModel>();
            if(query.Count != 0)
            {
                foreach (var item in query)
                {
                    SetupModel obj = new SetupModel();
                    obj.DepartmentId = item.DepartmentId;
                    obj.Name = item.Name;
                    list.Add(obj);
                }
                return View(list.ToList());
            }
            return View();
        }
        public ActionResult CreateDepartment()
        {   
            return PartialView("_Createdep", new SetupModel());
        }
        public ActionResult TableRendep()
        {
            return PartialView("_Tablerendep", new SetupModel());
        }
        public ActionResult Save(SetupModel model)
        {
            var msg = "";
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            Department obj = new Department();
            var chk = db.Departments.Where(x => x.Name == model.Name).FirstOrDefault();
            if (chk != null)
            {
                msg = "exist";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            
                obj.Name = model.Name;
                db.Departments.Add(obj);
                db.SaveChanges();
            msg = "save";
            return Json(msg, JsonRequestBehavior.AllowGet);
            
        }
        public ActionResult update(int id)
        {
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            var slid = db.Departments.Where(x => x.DepartmentId == id).SingleOrDefault();
            SetupModel model = new SetupModel();
            model.Name = slid.Name;
            model.hidep = slid.DepartmentId;
            return PartialView("_Createdep", model);
        }
        [HttpGet]
        public ActionResult updatesave(SetupModel model, int id)
        {
            var msg = "";
            var chk = db.Departments.Where(x => x.Name == model.Name).FirstOrDefault();
            if (chk != null)
            {
                msg = "exist";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var slid = db.Departments.Where(x => x.DepartmentId == id).SingleOrDefault();
                slid.Name = model.Name;
                msg = "update";
                db.SaveChanges();
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult DeleteDepartment(int id,SetupModel model)
        {
            var msg = "";
            var empid = db.Employees.Where(x => x.DepartmentId == id).FirstOrDefault();
            if (empid != null)
            {
                msg = "no";
                return Json(msg,JsonRequestBehavior.AllowGet);
            }
            else
            {
                IEnumerable<Designation> list = db.Designations.Where(x => x.DepartmentId == id).ToList();
                if (list != null)
                {
                    db.Designations.RemoveRange(list);
                }
                var depID = db.Departments.Where(x => x.DepartmentId == id).FirstOrDefault();
                db.Departments.Remove(depID);
                db.SaveChanges();
                msg = "Delete";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult AddDesignation()
        {

            var res = db.Designations.ToList();
            ViewBag.fkDepartmentId = new SelectList(res, "Designation_Id", "Name");
            List<Designation> deslist = res;
            List<Department> deplist = db.Departments.ToList();
            var query = (from a in deslist
                         join b in deplist
                         on a.DepartmentId equals b.DepartmentId
                         select new
                         {
                             DesignationId = a.Designation_Id,
                             designationName = a.Name,  
                             DepartmentName =  b.Name
                         }
                         ).ToList();

            List<SetupModel> list = new List<SetupModel>();
            if (query.Count != 0)
            {
                foreach (var item in query)
                {
                    SetupModel obj = new SetupModel();
                    obj.Designation_Id = item.DesignationId;
                    obj.DesName = item.designationName;
                    obj.DepartmentName = item.DepartmentName;
                    list.Add(obj);
                }
                return View(list.ToList());
            }
            return View();
        }
        public ActionResult CreateDesignation()
        {
            var res = db.Departments.ToList();
            ViewBag.fkDepartmentId = new SelectList(res, "DepartmentId", "Name");
            return PartialView("_Createdes", new SetupModel());
        }
        public ActionResult TableRendes()
        {

            return PartialView("_Tablerendes", new SetupModel());
        }
        public ActionResult SaveDesignation(SetupModel model)
        {
            var msg = "";
            var res = db.Designations.ToList();
            ViewBag.fkDepartmentId = new SelectList(res, "Designation_Id", "Name");
            Designation obj = new Designation();
            var chk = db.Designations.Where(x => x.Name == model.DesName && x.DepartmentId == model.fkDepartmentId).FirstOrDefault();
            if (chk != null)
            {
                msg = "exist";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            obj.Name = model.DesName;
            obj.DepartmentId = model.fkDepartmentId;
            db.Designations.Add(obj);
            db.SaveChanges();
            msg = "save";
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public ActionResult updateDesignation(int id)
        {
            var res = db.Departments.ToList();
            ViewBag.fkDepartmentId = new SelectList(res, "DepartmentId", "Name");
            var slid = db.Designations.Where(x => x.Designation_Id == id).SingleOrDefault();
            SetupModel model = new SetupModel();
            model.DesName = slid.Name;
            model.fkDepartmentId = slid.DepartmentId.GetValueOrDefault();
            model.hides = slid.Designation_Id;
            return PartialView("_Createdes", model);
        }
        [HttpGet]
        public ActionResult updatesaveDesignation(SetupModel model, int id)
        {
            var msg = "";
            var res = db.Designations.ToList();
            ViewBag.fkDepartmentId = new SelectList(res, "Designation_Id", "Name");
            var chk = db.Designations.Where(x => x.Name == model.DesName && x.DepartmentId == model.DepartmentId).FirstOrDefault();
            if (chk != null)
            {
                msg = "exist";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var slid = db.Designations.Where(x => x.Designation_Id == id).SingleOrDefault();
                slid.Name = model.DesName;
                db.SaveChanges();
                msg = "update";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
                

            
        }
        public ActionResult DeleteDesignation(int id, SetupModel model)
        {
            var msg = "";
            var empid = db.Employees.Where(x => x.Designation_Id == id).FirstOrDefault();
            if (empid != null)
            {
                msg = "no";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var desID = db.Designations.Where(x => x.Designation_Id == id).FirstOrDefault();
                if (desID != null)
                {
                    db.Designations.Remove(desID);
                    db.SaveChanges();
                }
            }
            msg = "Delete";
            return Json(msg,JsonRequestBehavior.AllowGet);
        }
        //coment
        public ActionResult AddAllowance()
         {
            ViewBag.msg = TempData["data"];
            List<AllowanceType> alwlist = db.AllowanceTypes.ToList();
            List<EmployeeType> emplist = db.EmployeeTypes.ToList();
            var query = (from a in alwlist
                         join b in emplist
                         on a.EmployeeTypeId equals b.EmployeeTypeId
                         select new
                         {
                             AllowanceTypeI = a.AllowanceTypeId,
                             AllowanceType   = a.AllowanceType1 ,
                             EmployeeType = b.EmployeeType1,

                         }
                         ).ToList();

           
        List<SetupModel> list = new List<SetupModel>();
        if (query.Count != 0)
        {
            foreach (var item in query)
            {
                SetupModel obj = new SetupModel();
                obj.AllowancTypeid = item.AllowanceTypeI;
                obj.allowanceType = item.AllowanceType;
                obj.EmployeeTypeName = item.EmployeeType;
                list.Add(obj);
            }
            return View(list.ToList());
        }
        return View();
    }
    public ActionResult CreateAllowance()
    {
            var res1 = db.EmployeeTypes.ToList();

sajidkhurshidm-payroll-a42b661a948c/payrollado/Views/Login/Index.cshtml
@model payrollado.Models.LoginSinup
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>
                @using (Html.BeginForm("Index", "Login", FormMethod.Post))
                {
                    @Html.ValidationSummary()
                    <div class="input-group mb-3">
                        @Html.TextBoxFor(x => x.UserName, htmlAttributes: new { @class = "form-control" , @placeholder= "UserName" })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa fa-user-circle"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.PasswordFor(x => x.Password, htmlAttributes: new { @class = "form-control",@placeHolder= "Password" })<br />
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </div>
                    <br/>
                    @*<input type="submit" value="Login" />*@
               
            }
           </div>
        </div>
<div class="text-danger">
    @ViewBag.Msg
</div>

    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    
</body>
</html>

sajidkhurshidm-payroll-a42b661a948c/payrollado/Views/Login/_Authorize.cshtml
@model List<payrollado.Models.LoginSinup>
<table class="table-responsive">
        <tr>
            <th>User Id</th>
            <th>User Name</th>
            <th>Password</th>
            <th>User Type</th>
        </tr>
        <tr>
            @foreach (var item in Model )
            {
                <td>@(item.) </td>
                <td>@(item.)</td>
                <td>@(item.)</td>
                <td>@(item)</td>
                <td><button style="width:100%; height:100%;" class="btn btn-success myclass" value="@item.UserId">Edit</button></td>
                <td><a style="width:100%; height:100%;" class="btn btn-danger" href="@Url.Action("DeleteAllowance","Master", new { id = @item.UserId })"><span>Delete</span></a></td>
            }
        </tr>
    </table>