sajidkhurshidm-payroll-a42b661a948c/payrollado/Controllers/EmployeeSalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using payrollado.Models;
using System.Data.Entity;
namespace payrollado.Controllers
{    
    public class EmployeeSalaryController : Controller
    {
        payrollEntities4 db = new payrollEntities4();
        // GET: EmployeeSalary
        public ActionResult Index(int? id)
        {
            if (Session["EmployeeId"] != null)
            {
                EmployeeSalaryM model = new EmployeeSalaryM();
                var res = db.EmployeeTypes.ToList();
                ViewBag.EmployeeTypeId = new SelectList(res, "EmployeeTypeId", "EmployeeType1");
                var res1 = db.LeaveTypes.ToList();
                ViewBag.LeaveTypeId = new SelectList(res1, "LeaveTypeId", "LeaveName");
                var res2 = db.Deductions.ToList();
                ViewBag.DeductionId = new SelectList(res2, "DeductionId", "DeductionName");
                ViewBag.EmployeeId = new SelectList("");
                ViewBag.AllowanceTypeId = new SelectList("");
                if(id.HasValue)
                {
                    var res3 = db.Employees.ToList();
                    var res4 = db.AllowanceTypes.ToList();
                    var empsal = db.EmployeeSalaries.Where(x => x.EmployeeSalaryId == id).FirstOrDefault();
                    model.BasicSelary = empsal.BasicSelary.GetValueOrDefault();
                    model.TotalAmount = empsal.TotalAmount.GetValueOrDefault();
                    model.hid = empsal.EmployeeSalaryId;
                    model.EmployeeId = empsal.EmployeeId.GetValueOrDefault();
                    ViewBag.EmployeeId = new SelectList(res3, "EmployeeId", "FirstName", empsal.EmployeeId);

                    var emptyp = db.Employees.Where(w => w.EmployeeId == empsal.EmployeeId).FirstOrDefault().EmployeeTypeId;
                    model.EmployeeTypeId = emptyp;

                    var alwtype = db.EmployeeAllowances.Where(w => w.EmployeeSalaryId == id).FirstOrDefault().AllowanceType.AllowanceTypeId;
                    ViewBag.AllowanceTypeId = new SelectList(res4, "AllowancetypeId", "AllowanceType1", alwtype);
                    model.employeeAllowances = db.EmployeeAllowances.Where(w => w.EmployeeSalaryId == empsal.EmployeeSalaryId).
                   Select(s => new EmployeeAllowenceM
                   {
                       AllowanceAmount = s.AllowanceAmount,
                       AllowanceTypeId = s.AllowanceTypeId,
                       AllowenceTypeName = s.AllowanceType.AllowanceType1,
                       EmployeeAllowanceId = s.EmployeeAllowanceId,
                       EmployeeSalaryId = s.EmployeeSalaryId
                   }).ToList();

                    model.employeeDeductions = db.EmployeeDeductions.Where(w => w.EmployeeSalaryId == empsal.EmployeeSalaryId).
                    Select(s => new EmployeedeductionM
                   {
                  EmployeeDedeuctionId = s.EmployeeDedeuctionId,
                  DeductionAmount = s.DeductionAmount,
                  EmployeeSalaryId = s.EmployeeSalaryId,
                  DeductionId = s.DeductionId,
                  deductionTypeName = s.Deduction.DeductionName
                   }).ToList();

                    model.EmployeeLeaves = db.EmployeeLeaves.Where(w => w.EmployeeSalaryId == empsal.EmployeeSalaryId).
                       Select(s => new EmployeeleaveM
                       {
                           EmployeeLeaveTypeId = s.EmployeeLeaveTypeId,
                           LeaveDays = s.LeaveDays,
                           LeaveTypeId = s.LeaveTypeId,
                           EmployeeSalaryId = s.EmployeeSalaryId,
                           leaveTypeName = s.LeaveType.LeaveName
                       }).ToList();
                    return View(model);
                }
                else
                {
                    model.employeeDeductions = null;
                    model.employeeAllowances = null;
                    model.EmployeeLeaves = null;
                    return View(model);
                }
            }

                return RedirectToAction("Index", "Login"); 
        }
        [HttpPost]
        public ActionResult Index(EmployeeSalaryM modal)
        {
            var msg = "";
            var res3 = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res3, "EmployeeId", "FirstName");
            var res = db.EmployeeTypes.ToList();
            ViewBag.EmployeeTypeId = new SelectList(res, "EmployeeTypeId", "EmployeeType1");
            var res1 = db.LeaveTypes.ToList();
            ViewBag.LeaveTypeId = new SelectList(res1, "LeaveTypeId", "LeaveName");
            var res2 = db.Deductions.ToList();
            ViewBag.DeductionId = new SelectList(res2, "DeductionId", "DeductionName");
            var res5 = db.AllowanceTypes.ToList();
            ViewBag.AllowanceTypeId = new SelectList(res5, "AllowanceTypeID", "AllowanceType1");

            var id = modal.hid;
            if (id == 0)
            {
                EmployeeSalary obj = new EmployeeSalary();
                obj.BasicSelary = modal.BasicSelary;
                obj.TotalAmount = modal.TotalAmount;
                obj.EmployeeId = modal.EmployeeId;
                obj.CreatedBy = modal.EmployeeId;
                obj.CreatedAt = DateTime.Now;
                db.EmployeeSalaries.Add(obj);
                db.SaveChanges();
                if (modal.employeeAllowances != null)
                {
                    foreach (var item in modal.employeeAllowances)
                    {
                        EmployeeAllowance obj2 = new EmployeeAllowance();
                        obj2.AllowanceAmount = item.AllowanceAmount;
                        obj2.AllowanceTypeId = item.AllowanceTypeId.GetValueOrDefault();
                        obj2.EmployeeSalaryId = obj.EmployeeSalaryId;
                        db.EmployeeAllowances.Add(obj2);
                    }
                }
                if (modal.employeeDeductions != null)
                {
                    foreach (var item2 in modal.employeeDeductions)
                    {
                        EmployeeDeduction obj3 = new EmployeeDeduction();
                        obj3.DeductionId = item2.DeductionId.GetValueOrDefault();
                        obj3.DeductionAmount = item2.DeductionAmount;
                        obj3.EmployeeSalaryId = obj.EmployeeSalaryId;
                        db.EmployeeDeductions.Add(obj3);
                    }
                }
                if (modal.EmployeeLeaves != null)
                {
                    foreach (var item3 in modal.EmployeeLeaves)
                    {
                        EmployeeLeave obj4 = new EmployeeLeave();
                        obj4.LeaveTypeId = item3.LeaveTypeId.GetValueOrDefault();
                        obj4.LeaveDays = item3.LeaveDays;
                        obj4.EmployeeSalaryId = obj.EmployeeSalaryId;
                        db.EmployeeLeaves.Add(obj4);
                    }
                }
                db.SaveChanges();
                 msg = "Save";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }

            //var empchk = db.EmployeeAllowances.Where(w => w.EmployeeAllowanceId == modal ;



            var empsalu = db.EmployeeSalaries.Where(w => w.EmployeeSalaryId == id).FirstOrDefault();          
            empsalu.BasicSelary = modal.BasicSelary;
            empsalu.TotalAmount = modal.TotalAmount;
            empsalu.EmployeeId = modal.EmployeeId;
            empsalu.CreatedBy = modal.EmployeeId;
            empsalu.CreatedAt = DateTime.Now;
            db.SaveChanges();


            if(modal.deletealws != null)
            {
                foreach(var itemdel in modal.deletealws)
                {
                    var del = db.EmployeeAllowances.Where(w => w.EmployeeAllowanceId == itemdel.EmployeeAllowanceId).FirstOrDefault();
                    db.EmployeeAllowances.Remove(del);
                }
                db.SaveChanges();
            }

            if (modal.deletelevs != null)
            {
                foreach (var itemdel in modal.deletelevs)
                {
                    var del = db.EmployeeLeaves.Where(w => w.EmployeeLeaveTypeId == itemdel.EmployeeLeaveTypeId).FirstOrDefault();
                    db.EmployeeLeaves.Remove(del);
                }
                db.SaveChanges();
            }
            if (modal.deleteducs != null)
            {
                foreach (var itemdel in modal.deleteducs)
                {
                    var del = db.EmployeeDeductions.Where(w => w.EmployeeDedeuctionId == itemdel.EmployeeDedeuctionId).FirstOrDefault();
                    db.EmployeeDeductions.Remove(del);
                }
                db.SaveChanges();
            }


            if (modal.employeeAllowances != null)
            {

                foreach (var item in modal.employeeAllowances)
                {
                    EmployeeAllowance obj2 = new EmployeeAllowance();
                    var del = db.EmployeeAllowances.Where(w => w.EmployeeAllowanceId == item.EmployeeAllowanceId).FirstOrDefault();
                    if (del != null)
                    {
                        db.EmployeeAllowances.Remove(del);
                    }
                    obj2.AllowanceAmount = item.AllowanceAmount;
                    obj2.AllowanceTypeId = item.AllowanceTypeId.GetValueOrDefault();
                    obj2.EmployeeSalaryId = id;
                    db.EmployeeAllowances.Add(obj2);
                    db.SaveChanges();
                }
            }
            //var emplev = db.EmployeeLeaves.Where(w => w.EmployeeLeaveTypeId == modal.).FirstOrDefault();
            if (modal.EmployeeLeaves != null)
            {
                foreach (var item3 in modal.EmployeeLeaves)
                {

sajidkhurshidm-payroll-a42b661a948c/payrollado/Views/EmployeeSalary/list.cshtml
@model List<payrollado.Models.Sallist>
@{         
  ViewBag.Title = "list";
}
@section Styles{
    @*<style>
            span.error {
                display: block;
                visibility: hidden;
                color: red;
                font-size: 80%;
            }

            tr.error {
                background-color: rgba(255,0,0,0.35);
            }
        </style>*@
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
}
<div class="card">
    <div class="card-body">
        <table id="mytable" class="table-bordered">
            <thead>
                <tr>
                    <th>Employee Id</th>
                    <th>Full Name</th>
                    <th>Basic Salary</th>
                    <th>Total Amount</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                 @foreach (var item in Model)
                 {
                <tr>
                    <td>@item.EmployeeId</td>
                    <td>@item.FirstName &nbsp; @item.LastName </td>
                    <td>@item.BasicSelary </td>
                    <td>@item.TotalAmount</td>
                    <td><a style="width:100%; height:100%;" class="btn btn-success" href="@Url.Action("Index","EmployeeSalary", new { id = @item.EmployeeSalaryId })"><span>Edit</span></a></td>
                    <td><a style="width:100%; height:100%;" class="btn btn-danger" href="@Url.Action("ListDelete","EmployeeSalary", new { id = @item.EmployeeSalaryId })"><span>Delete</span></a></td>   
                </tr>
                 }
            </tbody>
        </table>
    </div>
</div>

                  


    @section
    Scripts
    {
        <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript">

            $(document).ready(function () {
                $('#mytable').DataTable();
            });

        </script>
    }

sajidkhurshidm-payroll-a42b661a948c/payrollado/Views/EmployeeSalary/updates.cshtml
@model payrollado.Models.EmployeeSalaryM

@{
    ViewBag.Title = "updates";
}
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("updates", "EmployeeSalary", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(x => x.EmployeeTypeId)
                    @Html.DropDownListFor(x => x.EmployeeTypeId, null, "----SelectEmployeeId---- ", new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(x => x.EmployeeId)
                    @Html.DropDownListFor(x => x.EmployeeId, new SelectList(""), "----SelectEmployeeId---- ", new { @class = "form-control" })
                    @*//new SelectList(""),"Select EmployeeType"*@
                </div>
                <div class="col-md-3">
                    <div>
                        @Html.LabelFor(x => x.AllowanceTypeId)
                        @Html.DropDownListFor(x => x.AllowanceTypeId, new SelectList(""), "----SelectEmployeeId---- ", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(x => x.AlloawnceAmount)
                    @Html.TextBoxFor(x => x.AlloawnceAmount, new { @class = "form-control input-sm text-right amount" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(x => x.DeductionId)
                    @Html.DropDownListFor(x => x.DeductionId, null, "----SelectDeduction---", new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(x => x.DeductionAmount)
                    @Html.TextBoxFor(x => x.DeductionAmount, htmlAttributes: new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(x => x.LeaveTypeId)
                    @Html.DropDownListFor(x => x.LeaveTypeId, null, "-----SELECTLIST----", new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(x => x.LeaveDays)
                    @Html.TextBoxFor(x => x.LeaveDays, new { @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3" style="float:left;">
                    @Html.LabelFor(x => x.BasicSelary)
                    @Html.TextBoxFor(x => x.BasicSelary, new { @class = "form-control input-sm text-right amount" })
                </div>

                <div class="col-md-3" style="margin-left:50px; float:right; ">
                    @Html.LabelFor(x => x.TotalAmount)
                    @Html.TextBoxFor(x => x.TotalAmount, new { @class = "form-control" })
                    @Html.HiddenFor(x => x.EmployeeSalaryId)
                </div>



            </div>
            <input type="button" value="Save" id="Save" />
        }
       </div>
    </div>
                @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
                <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
                <script type="text/javascript">
                    $(function () {
                        var totalamount = function () {
                            var sum = 0;
                            $('.amount').each(function(){
                                var num = $(this).val();
                                if (num != 0) {
                                    sum += parseFloat(num);
                                }
                            });
                            $(TotalAmount).val(sum.toFixed(2));
                        }
                        $('.amount').keyup(function () {
                            totalamount();
                        });
                    });
                    document.getElementById('EmployeeTypeId').addEventListener("change", allowanc);
                    document.getElementById('EmployeeTypeId').addEventListener("change", Employee);
                    function allowanc() {
                        debugger;
                        var EmployeeTypeId = $('#EmployeeTypeId option:selected').val();
                        $.ajax({
                            method: 'Get',
                            url: '@Url.Action("EmployeeId", "EmployeeSalary")',
                            data: { EmployeeTypeId: EmployeeTypeId },
                            success: function (result) {
                                var fill = '<option value="-1" >Select</option>'
                                for (var i = 0; i < result.length; i++) {
                                    fill += '<option value="' + result[i].id + '">' + result[i].Name + '</option>';
                                }
                                $('#AllowanceTypeId').html(fill);
                            }
                        })
                    }
                    function Employee() {
                            var EmployeeTypeId = $('#EmployeeTypeId option:selected').val();
                            debugger;
                            $.ajax({
                                method: 'Get',
                                url: '@Url.Action("EmployeeTypeId", "EmployeeSalary")',
                                data: { EmployeeTypeId: EmployeeTypeId },
                                success: function (result) {
                                    var fill = '<option value="-1" >Select</option>'
                                    for (var i = 0; i < result.length; i++)
                                    {
                                        fill += '<option value="' + result[i].id + '">' + result[i].name + '</option>';
                                    }
                                    $('#EmployeeId').html(fill);
                                }
                               })
                    }*@
                @*$('#Save').click(function () {
                        debugger;
                        var emsal = $('#EmployeeSalaryId').val();

                        var info = {
                            "EmployeeTypeId": $('#EmployeeTypeId').val(),
                            "EmployeeId": $('#EmployeeId').val(),
                            "AllowanceTypeId": $('#AllowanceTypeId').val(),
                            "LeaveTypeId": $('#LeaveTypeId').val(),
                            "DeductionId": $('#DeductionId').val(),
                            "BasicSelary": $('#BasicSelary').val(),
                            "TotalAmount": $('#TotalAmount').val(),
                            "DeductionAmount": $('#DeductionAmount').val(),
                            "LeaveDays": $('#LeaveDays').val(),
                            "AlloawnceAmount": $('#DeductionAmount').val(),
                            "LeaveTypeIdName": $('#LeaveTypeId option:selected').text(),
                            "AllowanceTypeIdName": $('#AllowanceTypeId option:selected').text(),
                            "DeductionIdName": $('#DeductionId option:selected').text(),
                            "EmployeeTypeIdName": $('#EmployeeTypeId option:selected').text()
                        }
                        $.ajax({

                            type: 'Post',
                            url: '/EmployeeSalary/updates/?id=' + emsal,
                            data: JSON.stringify(info),
                            contentType: "application/json?charset=utf-8",
                            success: function (data, status, xhr) {
                            },
                        });
                    });
                </script>*@
                <h2>updates</h2>