sajidkhurshidm-payroll-a42b661a948c/payrollado/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using payrollado.Models;
namespace payrollado.Controllers
{
    public class SalaryController : Controller
    {
        payrollEntities4 db = new payrollEntities4();
        // GET: Salary
        public ActionResult Index()
        {
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            var query = db.multi().ToList(); 
            List<SalaryModel> list = new List<SalaryModel>();
            if (query.Count !=  0)
            {
                foreach (var item in query)
                {
                    SalaryModel obj = new SalaryModel();
                    obj.SalaryId = item.SalaryId;
                    obj.EmployeeId = item.EmployeeId;
                    obj.SalaryMonth = item.SalaryMonth.GetValueOrDefault();
                    obj.FirstName = item.FirstName;
                    obj.LastName = item.LastName;
                    obj.TotalAmount = item.TotalAmount.GetValueOrDefault();
                    list.Add(obj);
                }
                return View(list.ToList());
            }
            return View();
        }
        public ActionResult Create()
        {
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            return PartialView("_Create", new SalaryModel());
        }
        public ActionResult TableRend()
        {
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            return PartialView("_Tablerend", new SalaryModel() );
        }
        public ActionResult EmployeeId(SalaryModel model)
        {
            List<SalaryModel> list = new List<SalaryModel>();
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            var res2 = db.res(model.EmployeeId).ToList();
            if (res2 != null)
            {
                foreach (var item in res2)
                {
                    SalaryModel obj = new SalaryModel();
                    obj.BasicSalary = item.BasicSelary.GetValueOrDefault();
                    obj.AllowanceAmount = item.AllowanceAmount.GetValueOrDefault();
                    obj.TotalAbsent = item.TotalAbsent.GetValueOrDefault();
                    obj.EmployeeTotalAmount = item.TotalAmount.GetValueOrDefault();
                    obj.AllowanceType = item.AllowanceType;
                    obj.DeductionName = item.DeductionName;
                    obj.DeductionAmount = item.DeductionAmount;
                }
                return Json(list.ToList(), JsonRequestBehavior.AllowGet);
            }
            return Json(JsonRequestBehavior.AllowGet);
        }
        public ActionResult Save(SalaryModel model)
        {
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            Salary obj = new Salary();
            obj.EmployeeId = model.EmployeeId;
            obj.SalaryMonth=  model.SalaryMonth;
            obj.TotalAmount = model.NetAmount;
            db.Salaries.Add(obj);
            db.SaveChanges();
            var msg = "DATA HAS BEEN SAVE";
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public ActionResult update(int id)
        {
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            var res2 = db.res(id).FirstOrDefault();
            SalaryModel model = new SalaryModel();
            if (res2 != null)
            {
               
                model.EmployeeId = res2.EmployeeId;
                model.SalaryMonth = res2.SalaryMonth.GetValueOrDefault();
                model.NetAmount = res2.TotalAmount.GetValueOrDefault();
                model.BasicSalary = res2.BasicSelary.GetValueOrDefault();
                model.AllowanceType = res2.AllowanceType;
                model.TotalAbsent = res2.TotalAbsent.GetValueOrDefault();
                model.hid = res2.SalaryId.GetValueOrDefault();
               
            }
            return PartialView("_Create", model);
        }
        [HttpGet]
        public ActionResult updatesave(SalaryModel model, int id )
        {
            var res = db.Employees.ToList();
            ViewBag.EmployeeId = new SelectList(res, "EmployeeId", "FirstName");
            var slid = db.Salaries.Where(x => x.SalaryId == id).SingleOrDefault();
            slid.EmployeeId = model.EmployeeId;
            slid.SalaryMonth = model.SalaryMonth;
            slid.TotalAmount = model.NetAmount;
            db.SaveChanges();
            var msg = "Data Has Been Updated";
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeleteSalary(int id)
        {
            var msg = "";
            var salID = db.Salaries.Where(x => x.SalaryId == id).FirstOrDefault();
            if (salID != null)
            {
                db.Salaries.Remove(salID);
                db.SaveChanges();
            }
            msg = "delete";
            return Json(msg,JsonRequestBehavior.AllowGet);  
        }
    }
}

sajidkhurshidm-payroll-a42b661a948c/payrollado/Views/Salary/Index.cshtml
@model List<payrollado.Models.SalaryModel>
@{
    ViewBag.Title = "Index";
}

@section Styles {
    <link href="~/Scripts/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" />
    
        <style>
            span.error {
                display: block;
                visibility: hidden;
                color: red;
                font-size: 80%;
            }

            tr.error {
                background-color: rgba(255,0,0,0.35);
            }
        </style>
    
}
<button class="btn btn-primary" id="call" style="margin-top:30px;">Generate Salary</button>
<div id="part">
</div>
@{
    payrollEntities4 db = new payrollEntities4();
    var chk = db.multi().ToList();
    if (chk.Count != 0)
    {
        @Html.Partial("_Tablerend", Model)

    }
}

@section Models
    {
    <div id="myModal" class="modal fade" tabindex="-1">
        <div class="modal-lg  modal-dialog ">
            <div class="modal-content">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Please Add a Salary </h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div id="dvCreate"></div>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-success" style="margin-top:15px;" value="Save" id="Save" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section
    scripts
        {
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/Scripts/bootbox.js"></script>
    <script type="text/javascript">

        $('.myclass').click(function () {
            debugger;
            var id = $(this).val();
                //$('.myclass').data('id');
            $.ajax({
                type: 'Get',
                url: '/Salary/update?id=' + id,
                contentType: "application/json",
                dataType: 'html',
                success: function (data) {
                    debugger;
                    $('#dvCreate').html(data);
                    $("#myModal").modal();
                    $('#SalaryMonth').datepicker({
                        format: 'yyyy-mm-dd',
                        orientation: "bottom auto",
                        autoclose: true
                    });
                    $('#AllowanceAmount').change(function () {
                        allowance();
                    });
                },
                error: function (error) {
                    console.log(error)
                }
            });
        });
        $('.myclassdel').click(function () {
            debugger;
            var id = $(this).val();
            bootbox.confirm("Do You Really want to delete record? ", function (result) {
                if (result) {
                    debugger;
                    $.ajax({
                        type: 'Get',
                        url: '/Salary/DeleteSalary?id=' + id,
                        contentType: "application/json?charset=utf-8",
                        success: function (data) {
                            debugger;
                            $("#mymodal").modal("hide");
                            location.reload();

                        },
                    })
                }
            })
        })

        function allowance() {
            debugger;
            var sum = 0;
            var b = $('#BasicSalary').val();
            var a = $('#AllowanceAmount').val();
            var ab = $('#TotalAbsent').val();
            var day = 30;
            var div = (b / day).toFixed(2) * ab;
            var bf = parseFloat(b);
            var af = parseFloat(a);
            if (a == "")
            {
                sum = (b + 0) - div;
            }
            else
            {
               sum  = (bf + af) - div;

            }
           
            $('#NetAmount').val(sum.toFixed(2))
        }

        $('#call').click(function () {
            debugger;
            $.ajax({
                type: 'Get',
                url: '/Salary/Create',
                contentType: "application/json",
                dataType: 'html',
                success: function (data) {
                    debugger;
                    $('#dvCreate').html(data);
                    $("#myModal").modal();
                    $('#SalaryMonth').datepicker({
                        format: 'dd-MM-yyyy',
                        orientation: "bottom auto",
                        autoclose: true
                    });
                    $("#EmployeeId").on("change", function () {
                        EmployeeId();                        
                        if ($('#EmployeeId option:selected').text() == "---Select---") {
                            $('#EmployeeId').siblings('span.error').css('visibility', 'visible');
                        }
                        else
                        {
                            $('#EmployeeId').siblings('span.error').css('visibility', 'hidden');
                        }
                    });
                    $('#AllowanceAmount').change(function () {
                        allowance();
                    });
                    $('#SalaryMonth').change(function () { 
                    if ($('#SalaryMonth').val() == "01/01/0001 00:00:00") {
                        $('#SalaryMonth').siblings('span.error').css('visibility', 'visible');
                    }
                    else {
                        $('#SalaryMonth').siblings('span.error').css('visibility', 'hidden');
                        }
                    })
                   },
                error: function (error) {
                    console.log(error)
                }
            });
        });

        function EmployeeId() {
            var EmployeeId = $('#EmployeeId option:selected').val();
            debugger;
            $.ajax({
                method: 'Get',
                url: '@Url.Action("EmployeeId", "Salary")',
                data: { EmployeeId: EmployeeId },
                success: function (result) {
                    console.log(result);
                    debugger;
                    for (var i = 0; i < result.length; i++)
                    {
                        $('#BasicSalary').val(result[i].BasicSalary)
                    }
                    $('#BasicSalary').val(result[0].BasicSalary);
                    $('#AllowanceAmount').val(result[0].AllowanceAmount);
                    $('#TotalAbsent').val(result[0].TotalAbsent);
                    $('#EmployeeTotalAmount').val(result[0].EmployeeTotalAmount);
                    $('#AllowanceType').val(result[0].AllowanceType);
                    var bs = $('#BasicSalary').val();
                    var abst = $('#TotalAbsent').val();
                    var day = 30
                    var res = bs / day * abst
                    $('#deducAmount').val(res.toFixed(2));
                    var al = $('#AllowanceAmount').val();
                    var dc = $('#deducAmount').val();
                    var bsc = parseFloat(bs)
                    var alc = parseFloat(al)
                    var dsc = parseFloat(dc)
                    var sum = bsc + alc - dsc;
                    $('#NetAmount').val(sum.toFixed(2))
                }
            })
        }
        $('#Save').click(function ()
        {
            var isallvalid = true;
            if ($('#EmployeeId option:selected').text() == "---Select---") {
                $('#EmployeeId').siblings('span.error').css('visibility', 'visible');
                isallvalid = false;
            }
            else
            {
                $('#EmployeeId').siblings('span.error').css('visibility', 'hidden');
            }
            if ($('#SalaryMonth').val() == "01/01/0001 00:00:00") {
                $('#SalaryMonth').siblings('span.error').css('visibility', 'visible');
                isallvalid = false;
            }
            else {
                $('#SalaryMonth').siblings('span.error').css('visibility', 'hidden');
            }
            if (isallvalid) {
                debugger;
                var chek = $('#hid').val();
                console.log(chek);
                if ($('#hid').val() == 0) {

                    var obj = {
                        SalaryMonth: $('#SalaryMonth').val(),
                        NetAmount: $('#NetAmount').val(),
                        EmployeeId: $('#EmployeeId').val()
                    }
                    $.ajax({
                        type: 'Post',
                        url: '/Salary/Save',
                        contentType: "application/json?charset=utf-8",
                        data: JSON.stringify(obj),
                        success: function (response) {
                            debugger;
                            $("#myModal").modal("hide");
                            location.reload();
                        },
                    })
                }

                else {
                    var id = $('#hid').val();
                    var obj2 = {
                        SalaryMonth: $('#SalaryMonth').val(),
                        NetAmount: $('#NetAmount').val(),
                        EmployeeId: $('#EmployeeId').val()
                    }
                    $.ajax({
                        type: 'Get',
                        url: '/Salary/updatesave?id=' + id,
                        contentType: "application/json?charset=utf-8",
                        data: JSON.stringify(obj2),
                        success: function (response) {
                            debugger;
                            $("#mymodal").modal("hide");
                            location.reload();
                        }
                    })
                }
            }
          });
    </script>

}

sajidkhurshidm-payroll-a42b661a948c/payrollado/Views/Salary/_Create.cshtml
@model payrollado.Models.SalaryModel
@section Styles{
    <style>
        span.error {
            display: block;
            visibility: hidden;
            color: red;
            font-size: 80%;
        }

        tr.error {
            background-color: rgba(255,0,0,0.35);
        }
    </style>
}


@using (Html.BeginForm("Create", "Salary", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-6">
            @Html.LabelFor(x => x.EmployeeId)
            @Html.DropDownListFor(x => x.EmployeeId, null, "---Select---", new { @class = "form-control" })
            <span class="error">Please Select a Employee</span>
        </div>
        <div class="col-md-6">
            @Html.LabelFor(x => x.SalaryMonth)
            @Html.EditorFor(x => x.SalaryMonth , new { @class = "form-control" })
            <span class="error">Please Select a SalaryMonth</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            @Html.LabelFor(x => x.BasicSalary)
            @Html.TextBoxFor(x => x.BasicSalary, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(x => x.AllowanceAmount)
            @Html.TextBoxFor(x => x.AllowanceAmount, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(x => x.AllowanceType)
            @Html.TextBoxFor(x => x.AllowanceType, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(x => x.TotalAbsent)
            @Html.TextBoxFor(x => x.TotalAbsent, new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            @Html.LabelFor(x => x.deducAmount)
            @Html.TextBoxFor(x => x.deducAmount, new { @class = "form-control" })
          </div>
        <div class="col-md-3">
            @Html.LabelFor(x => x.NetAmount)
            @Html.TextBoxFor(x => x.NetAmount, new { @class = "form-control" })
         </div>
            @Html.HiddenFor(x => x.hid)

        </div>

}

sajidkhurshidm-payroll-a42b661a948c/payrollado/Views/Salary/_Tablerend.cshtml
@model List<payrollado.Models.SalaryModel>
<div class="wrapper" style="padding:20px 20px 20px 20px;">
    <div style="margin-top:20px">
        <div class="card">
            <div class="card-body table-responsive ">
                <table border="1" class="table-bordered container-fluid ">
                    <thead>
                        <tr>
                            <th>Salary Id</th>
                            <th>Full Name</th>
                            <th>Salary Amount</th>
                            <th>Salary Month</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr id="row">
                            <td>@(item.SalaryId != 0 ? item.SalaryId : 0)</td>
                            <td>@item.FirstName  &nbsp;  @item.LastName </td>
                            <td>@(item.TotalAmount != 0 ? item.TotalAmount : 0)</td>
                            <td>@item.SalaryMonth.ToLongDateString()</td>
                            <td><button class="btn btn-success myclass" style="width:100%; height:100%;" value="@item.EmployeeId">Edit</button></td>
                            <td><button class="btn btn-danger myclassdel" style="width:100%; height:100%;" value="@item.SalaryId">Delete</button></td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>